# a,b=map(int,input().split())
# result =bool(a % b ==0)
# print(result)
# a = str(input())
# b = str(input())
# print(a+' '+b)
# a,b=map(str,input().split())
# print((a+' ')*2+((b+' ')*3))
# a,b=map(int,input().split())
# print(f"Переменная a = {a}, переменная b = {b}")
# a = str(input())
# b = len(a)
# print(f"Строка: {a}. Длина: {b}")
# a, b = map(str, input().split())
# print(a in b, a == b , a > b , a < b)
# a, b = map(str, input().split())
# a1=ord(a)
# b1=ord(b)
# # print(f"Коды: {a} = {a1}, {b} = {b1}")
# a = str(input())
# print(a.find('ra'))
# a, b, c = input().split()
# print(a.rjust(3, '0'), b.rjust(3, '0'), c.rjust(3, '0'), sep='\n')
# a = str(input())
# print(a.replace(' ', ';'))
# a = 'Тема занятия "спецсимволы"'
# print(a)
# a, b = map(str, input().split())
# print(a+'\\'+b)
# a = str(input()).replace(' ', '\'', 1).replace(' ', '\"')
# print(a)
# a = r"C:\WINDOWS\System32\drivers\etc\hosts"
# print(a)
# a = str(input())
# print('\"'+a+'\"')
# name = str(input())
# familia = str(input())
# age = int(input())
# print(f"Уважаемый {name} {familia}! Поздравляем Вас с {age}-летием!")
# a, b, c= map(int, input().split())
# print(f"Габариты: {a} x {b} x {c}")
# city = str(input())
# street = str(input())
# house = int(input())
# apartment = int(input())
# print(f"г. {city}, ул. {street}, д. {house}, кв. {apartment}")
curs = float(input())
rubl = int(input())
dollars = int(rubl//curs)
print(f"Вы можете получить {dollars}$ за {rubl} рублей по курсу {curs}")
